### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by akoksal** [iorixxx/lucene-solr-analysis-turkish#7]
The build have several errors when I run "mvn clean package dependency:copy-dependencies" command after I cloned the repo. Errors are same as in [travis-ci](https://travis-ci.org/iorixxx/lucene-solr-analysis-turkish).

Do I need to do something else to generate jar files or is this code still in development for zemberek 0.14 and solr 7.4?

**Comment by iorixxx** [comment]
Carrot test framework does not like new zemberek.  Quick fix is to disable test during maven build via -DskipTests flag. Ideal fix is to dig into zemberek code, verify this is a issue in zemberek. Or report this to zemberek. Can you file a issue in zemberek ?
